apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 5m
  url: https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  releaseName: argocd
  chart:
    spec:
      chart: argocd
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: argocd
      version: v5.13.0
  interval: 5m

