apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubed-deploy
  namespace: flux-system
spec:
  interval: 1m
  path: ./config/base/applications/kubed/fluxv2/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches: []
