apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubed-deploy
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./config/base/applications/kubed/fluxv2/deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches:
    - patch: |
       - op: replace
         path: /spec/values/config/clusterName
         value: gke-pe-dev
      target:
        kind: HelmRelease
        group: helm.toolkit.fluxcd.io
        name: kubed
        namespace: kubed
