# following this pattern as cert-manager helm chart creates its CRDs
# https://github.com/fluxcd/flux2/discussions/1916
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kubed-deploy.yaml
- deploy/
