apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-issuer-deploy
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./config/base/applications/cert-manager-issuers/fluxv2/deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches: []
  dependsOn:
    - namespace: flux-system
      name: cert-manager-deploy