apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
#- monitoring/argocd-dashboard.yaml
#- monitoring/argocd-metrics-sm.yaml
#- monitoring/argocd-repo-server-metrics-sm.yaml
#- monitoring/argocd-server-metrics-sm.yaml
- argocd/
