apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  namespace: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-v1
      version: v1
  template:
    metadata:
      labels:
        app: helloworld-v1
        version: v1
    spec:
      containers:
      - name: helloworld
        image: istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: certs
          mountPath: "/etc/java/"
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: hello-cert
