apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/applications/kubed/fluxv2/
- ../../../base/applications/argocd/fluxv2/
- ../../../base/applications/cert-manager/fluxv2
- ../../../base/applications/cert-manager-issuers/fluxv2
- ../../../base/applications/weave-gitops-dashboard/fluxv2
- flux-system/
transformers:
- transformers/kubed.yaml
#- transformers/weave-gitops-dashboard.yaml