apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/applications/kubed/fluxv2/
- ../../../base/applications/cert-manager/fluxv2
- ../../../base/applications/cert-manager-issuers/fluxv2
- flux-system/
transformers:
- transformers/kubed.yaml
