apiVersion: builtin
kind: PatchTransformer
metadata:
  name: kubed-deploy
target:
  group: kustomize.toolkit.fluxcd.io
  kind: Kustomization
  name: kubed-deploy
  namespace: flux-system
patch: |-
  - op: add
    path: /spec/patches/-
    value:
      target:
        kind: HelmRelease
        group: helm.toolkit.fluxcd.io
        name: kubed
        namespace: kubed
      patch: |-
      - op: replace
        path: /spec/values/config/clusterName
        value: gke-pe-dev

