apiVersion: builtin
kind: PatchTransformer
metadata:
  name: kubed-deploy
target:
  group: kustomize.toolkit.fluxcd.io
  kind: Kustomization
  name: kubed-deploy
  namespace: flux-system
patch: |-
  - op: add
    path: /spec/patches/-
    value:
      target:
        group: helm.toolkit.fluxcd.io
        kind: HelmRelease
        name: kubed
        namespace: kubed
      patch: |-
        - op: replace
          path: /spec/values/config/clusterName
          value: gke-pe-dev
  - op: add
    path: /spec/patches/-
    value:
      target:
        group: helm.toolkit.fluxcd.io
        kind: HelmRelease
        name: kubed
        namespace: kubed
      patch: |-
        - op: replace
          path: /spec/chart/spec/version
          value: v0.12.0

