apiVersion: builtin
kind: PatchTransformer
metadata:
  name: kubed-deploy
target:
  group: kustomize.toolkit.fluxcd.io
  kind: Kustomization
  name: kubed-deploy
  namespace: flux-system
patch: |-
  - op: replace
    path: /spec/values/config/cLusterName
    value: gke-pe-dev
