apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubed
  namespace: kubed
spec:
  interval: 5m
  url: https://charts.appscode.com/stable/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubed
  namespace: kubed
spec:
  releaseName: kubed
  chart:
    spec:
      chart: kubed
      sourceRef:
        kind: HelmRepository
        name: kubed
        namespace: kubed
      version: some-version
  interval: 5m
  values:
    config:
      clusterName: some-cluster